# Generated by Django 5.2 on 2026-05-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userprofile_password_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="username_changed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="系统用户名最近修改时间"),
        ),
    ]
