# Generated by Codex on 2026-05-25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userprofile_username_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=accounts.models.user_avatar_upload_path,
                verbose_name="头像",
            ),
        ),
    ]
