# Generated by Codex on 2026-05-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_userprofile_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username_snapshot", models.CharField(blank=True, default="", max_length=150, verbose_name="用户名快照")),
                (
                    "action",
                    models.CharField(
                        choices=[("login", "登录"), ("logout", "退出"), ("menu", "菜单访问")],
                        db_index=True,
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=120, verbose_name="操作内容")),
                ("path", models.CharField(blank=True, default="", max_length=500, verbose_name="页面路径")),
                ("method", models.CharField(blank=True, default="", max_length=12, verbose_name="请求方式")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 地址")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="浏览器信息")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="扩展信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="操作时间")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户操作日志",
                "verbose_name_plural": "用户操作日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="useroperationlog",
            index=models.Index(fields=["user", "-created_at"], name="acct_oplog_user_time_idx"),
        ),
        migrations.AddIndex(
            model_name="useroperationlog",
            index=models.Index(fields=["action", "-created_at"], name="acct_oplog_action_time_idx"),
        ),
    ]
