# Generated by Django 5.2 on 2026-04-09 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("langgraph_integration", "0022_alter_llmconfig_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLLMConfigPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户LLM偏好",
                "verbose_name_plural": "用户LLM偏好",
            },
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="该配置的所有者。为空时表示历史全局配置，仅超级管理员可管理。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_llm_configs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="归属用户",
            ),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="shared_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_llm_configs",
                to="auth.group",
                verbose_name="共享组织",
            ),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="shared_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_llm_configs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="共享成员",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="config_name",
            field=models.CharField(
                help_text="用户自定义的配置名称，如'生产环境OpenAI'、'测试Claude配置'",
                max_length=255,
                verbose_name="配置名称",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmconfig",
            constraint=models.UniqueConstraint(
                fields=("owner", "config_name"), name="unique_llm_config_name_per_owner"
            ),
        ),
        migrations.AddField(
            model_name="userllmconfigpreference",
            name="active_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_users",
                to="langgraph_integration.llmconfig",
                verbose_name="当前激活配置",
            ),
        ),
        migrations.AddField(
            model_name="userllmconfigpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_config_preference",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
