# Generated by Django 5.2 on 2026-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "langgraph_integration",
            "0023_userllmconfigpreference_llmconfig_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="wire_api",
            field=models.CharField(
                choices=[
                    ("chat_completions", "OpenAI Chat"),
                    ("messages", "Claude Messages"),
                ],
                default="chat_completions",
                help_text="OpenAI 兼容网关默认走 /chat/completions；如网关只兼容 Claude Messages，可切换为 /messages。",
                max_length=32,
                verbose_name="协议类型",
            ),
        ),
    ]
