# Generated by Django 5.2 on 2026-04-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langgraph_integration", "0024_llmconfig_wire_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai_compatible", "OpenAI 兼容"),
                    ("siliconflow", "硅基流动"),
                    ("qwen", "Qwen/通义千问"),
                ],
                default="openai_compatible",
                help_text="LLM服务供应商",
                max_length=50,
                verbose_name="供应商",
            ),
        ),
    ]
