# Generated by Django 5.2 on 2026-04-05 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_remove_project_password_remove_project_system_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFactoryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="标签名称")),
                ("code", models.CharField(max_length=120, verbose_name="引用编码")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="标签说明"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="标签颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_data_factory_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_factory_tags",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据工厂标签",
                "verbose_name_plural": "数据工厂标签",
                "db_table": "data_factory_tag",
                "ordering": ["project_id", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DataFactoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(max_length=100, verbose_name="工具编码"),
                ),
                (
                    "tool_category",
                    models.CharField(
                        choices=[
                            ("string", "字符工具"),
                            ("encoding", "编码工具"),
                            ("random", "随机工具"),
                            ("encryption", "加密工具"),
                            ("test_data", "测试数据"),
                            ("json", "JSON 工具"),
                            ("crontab", "Crontab 工具"),
                        ],
                        max_length=32,
                        verbose_name="工具分类",
                    ),
                ),
                (
                    "tool_scenario",
                    models.CharField(
                        choices=[
                            ("data_generation", "数据生成"),
                            ("format_conversion", "格式转换"),
                            ("data_validation", "数据验证"),
                            ("encryption_decryption", "加密解密"),
                        ],
                        max_length=32,
                        verbose_name="使用场景",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(blank=True, default=dict, verbose_name="输入数据"),
                ),
                (
                    "output_data",
                    models.JSONField(blank=True, default=dict, verbose_name="输出数据"),
                ),
                (
                    "is_saved",
                    models.BooleanField(default=True, verbose_name="是否保存"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_data_factory_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_factory_records",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="records",
                        to="data_factory.datafactorytag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据工厂记录",
                "verbose_name_plural": "数据工厂记录",
                "db_table": "data_factory_record",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="datafactorytag",
            index=models.Index(
                fields=["project", "name"], name="data_factor_project_c0b46f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datafactorytag",
            index=models.Index(
                fields=["project", "code"], name="data_factor_project_9d19aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datafactorytag",
            unique_together={("project", "code"), ("project", "name")},
        ),
        migrations.AddIndex(
            model_name="datafactoryrecord",
            index=models.Index(
                fields=["project", "-created_at"], name="data_factor_project_c3e208_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datafactoryrecord",
            index=models.Index(
                fields=["creator", "-created_at"], name="data_factor_creator_35ef16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datafactoryrecord",
            index=models.Index(
                fields=["project", "tool_category"],
                name="data_factor_project_91558a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datafactoryrecord",
            index=models.Index(
                fields=["project", "tool_scenario"],
                name="data_factor_project_17109f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datafactoryrecord",
            index=models.Index(
                fields=["project", "is_saved"], name="data_factor_project_b9c2f9_idx"
            ),
        ),
    ]
