# Generated by Django 5.2 on 2026-04-29 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0028_testbug_multi_assignees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="testbug",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="multi_assigned_test_bugs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="指派成员",
            ),
        ),
        migrations.AlterField(
            model_name="testbug",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
