# Generated by Django 5.2 on 2026-05-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0029_alter_testbug_assigned_users_alter_testbug_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="testbug",
            name="related_testcases",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_bugs",
                to="testcases.testcase",
                verbose_name="关联测试用例列表",
            ),
        ),
        migrations.AlterField(
            model_name="testbug",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("unassigned", "未指派"),
                    ("assigned", "未确认"),
                    ("confirmed", "已确认"),
                    ("fixed", "已修复"),
                    ("pending_retest", "待复测"),
                    ("expired", "已过期"),
                ],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
