# Generated by Django 5.2 on 2026-05-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0032_alter_testbug_bug_type_alter_testbug_resolution_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testreportsnapshot",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "测试报告快照",
                "verbose_name_plural": "测试报告快照",
            },
        ),
        migrations.AddField(
            model_name="testreportsnapshot",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="是否置顶"),
        ),
    ]
