# Generated by Django 5.2 on 2026-04-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('ui_automation', '0003_add_batch_execution_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiAICase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('task_description', models.TextField(verbose_name='任务描述')),
                ('default_execution_mode', models.CharField(choices=[('text', '文本模式'), ('vision', '视觉模式')], default='text', max_length=20, verbose_name='默认执行模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_ai_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_ai_cases', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI AI 用例',
                'verbose_name_plural': 'UI AI 用例',
                'db_table': 'ui_ai_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UiAIExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200, verbose_name='用例名称快照')),
                ('task_description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('execution_mode', models.CharField(choices=[('text', '文本模式'), ('vision', '视觉模式')], default='text', max_length=20, verbose_name='执行模式')),
                ('execution_backend', models.CharField(choices=[('planning', 'AI 规划'), ('browser_use', 'Browser Use')], default='planning', max_length=32, verbose_name='执行后端')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '成功'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='执行状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长（秒）')),
                ('logs', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('steps_completed', models.JSONField(blank=True, default=list, verbose_name='已完成步骤')),
                ('planned_tasks', models.JSONField(blank=True, default=list, verbose_name='规划任务')),
                ('screenshots_sequence', models.JSONField(blank=True, default=list, verbose_name='截图序列')),
                ('gif_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='GIF 路径')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('model_config_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='模型配置名称')),
                ('ai_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='ui_automation.uiaicase', verbose_name='关联 AI 用例')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_ai_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_ai_execution_records', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI AI 执行记录',
                'verbose_name_plural': 'UI AI 执行记录',
                'db_table': 'ui_ai_execution_record',
                'ordering': ['-start_time'],
            },
        ),
    ]
