# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0004_ui_ai_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiaicase',
            name='enable_gif',
            field=models.BooleanField(default=True, verbose_name='启用 GIF 录制'),
        ),
        migrations.AddField(
            model_name='uiaiexecutionrecord',
            name='enable_gif',
            field=models.BooleanField(default=True, verbose_name='启用 GIF 录制'),
        ),
    ]
