# Generated by Codex on 2026-03-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_automation", "0001_initial"),
        ("projects", "0004_remove_project_password_remove_project_system_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiTestCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160, verbose_name="测试用例名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="测试用例描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("ready", "ready"), ("disabled", "disabled")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                ("script", models.JSONField(blank=True, default=dict, verbose_name="接口脚本")),
                ("assertions", models.JSONField(blank=True, default=list, verbose_name="断言规则")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_test_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_test_cases",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="api_automation.apirequest",
                        verbose_name="关联请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 测试用例",
                "verbose_name_plural": "API 测试用例",
                "db_table": "api_automation_test_case",
                "ordering": ["-created_at"],
            },
        ),
    ]
