# Generated by Django 5.2 on 2026-03-31 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0002_apitestcase'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='源文档名称')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='进度百分比')),
                ('progress_stage', models.CharField(blank=True, default='', max_length=50, verbose_name='当前阶段')),
                ('progress_message', models.TextField(blank=True, default='', verbose_name='阶段说明')),
                ('generate_test_cases', models.BooleanField(default=True, verbose_name='是否生成测试用例')),
                ('enable_ai_parse', models.BooleanField(default=True, verbose_name='是否启用AI增强解析')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='结果载荷')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='api_automation.apicollection', verbose_name='目标集合')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_import_jobs', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API 导入任务',
                'verbose_name_plural': 'API 导入任务',
                'db_table': 'api_automation_import_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
