# Generated by Django 5.2 on 2026-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_automation", "0003_apiimportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiimportjob",
            name="cancel_requested",
            field=models.BooleanField(default=False, verbose_name="是否请求停止"),
        ),
        migrations.AlterField(
            model_name="apiimportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("running", "running"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("canceled", "canceled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="任务状态",
            ),
        ),
    ]
