# Generated by Django 5.2 on 2026-04-01 12:15

import json
import django.db.models.deletion
from django.db import migrations, models


LEGACY_TO_BODY_MODE = {
    "none": "none",
    "json": "json",
    "form": "form",
    "raw": "raw",
}


def _to_text(value):
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False)


def _legacy_assertions_to_specs(assertions):
    result = []
    if not isinstance(assertions, list):
        return result
    for index, item in enumerate(assertions):
        if not isinstance(item, dict):
            continue
        assertion_type = str(item.get("type") or "").strip()
        if not assertion_type:
            continue
        expected = item.get("expected")
        payload = {
            "enabled": True,
            "order": index,
            "assertion_type": assertion_type,
            "target": "body",
            "selector": str(item.get("path") or item.get("selector") or ""),
            "operator": str(item.get("operator") or "equals"),
            "expected_text": expected if isinstance(expected, str) else "",
            "expected_number": float(expected) if isinstance(expected, (int, float)) else None,
            "expected_json": expected if isinstance(expected, (dict, list, bool)) else {},
            "min_value": item.get("min"),
            "max_value": item.get("max"),
            "schema_text": "",
        }
        if assertion_type == "header":
            payload["target"] = "header"
        elif assertion_type == "cookie":
            payload["target"] = "cookie"
        elif assertion_type == "json_path":
            payload["target"] = "json"
        result.append(payload)
    return result


def _create_named_field_specs(model, fk_name, fk_id, field_kind, mapping):
    rows = []
    if not isinstance(mapping, dict):
        return rows
    for index, (name, value) in enumerate(mapping.items()):
        rows.append(
            model(
                **{
                    fk_name: fk_id,
                    "field_kind": field_kind,
                    "name": str(name),
                    "value": _to_text(value),
                    "enabled": True,
                    "order": index,
                }
            )
        )
    return rows


def _create_request_specs(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ApiRequest = apps.get_model("api_automation", "ApiRequest")
    ApiRequestSpec = apps.get_model("api_automation", "ApiRequestSpec")
    ApiRequestFieldSpec = apps.get_model("api_automation", "ApiRequestFieldSpec")
    ApiRequestAuthSpec = apps.get_model("api_automation", "ApiRequestAuthSpec")
    ApiRequestTransportSpec = apps.get_model("api_automation", "ApiRequestTransportSpec")
    ApiAssertionSpec = apps.get_model("api_automation", "ApiAssertionSpec")

    for request in ApiRequest.objects.using(db_alias).all().iterator():
        body_mode = LEGACY_TO_BODY_MODE.get(request.body_type or "none", "raw")
        body_json = request.body if body_mode == "json" and isinstance(request.body, (dict, list)) else {}
        raw_text = _to_text(request.body) if body_mode == "raw" else ""
        request_spec = ApiRequestSpec.objects.using(db_alias).create(
            request_id=request.id,
            method=request.method,
            url=request.url,
            body_mode=body_mode,
            body_json=body_json,
            raw_text=raw_text,
            xml_text="",
            binary_base64="",
            graphql_query="",
            graphql_operation_name="",
            graphql_variables={},
            timeout_ms=request.timeout_ms,
        )

        field_rows = []
        field_rows.extend(_create_named_field_specs(ApiRequestFieldSpec, "request_spec_id", request_spec.id, "header", request.headers))
        field_rows.extend(_create_named_field_specs(ApiRequestFieldSpec, "request_spec_id", request_spec.id, "query", request.params))
        if body_mode == "form" and isinstance(request.body, dict):
            field_rows.extend(_create_named_field_specs(ApiRequestFieldSpec, "request_spec_id", request_spec.id, "form", request.body))
        if field_rows:
            ApiRequestFieldSpec.objects.using(db_alias).bulk_create(field_rows)

        ApiRequestAuthSpec.objects.using(db_alias).create(
            request_spec_id=request_spec.id,
            auth_type="none",
            username="",
            password="",
            token_value="",
            token_variable="token",
            header_name="Authorization",
            bearer_prefix="Bearer",
            api_key_name="",
            api_key_in="header",
            api_key_value="",
            cookie_name="",
            bootstrap_request_id=None,
            bootstrap_request_name="",
            bootstrap_token_path="",
        )
        ApiRequestTransportSpec.objects.using(db_alias).create(
            request_spec_id=request_spec.id,
            verify_ssl=True,
            proxy_url="",
            client_cert="",
            client_key="",
            follow_redirects=True,
            retry_count=0,
            retry_interval_ms=500,
        )

        assertion_rows = [
            ApiAssertionSpec(
                request_id=request.id,
                enabled=payload["enabled"],
                order=payload["order"],
                assertion_type=payload["assertion_type"],
                target=payload["target"],
                selector=payload["selector"],
                operator=payload["operator"],
                expected_text=payload["expected_text"],
                expected_number=payload["expected_number"],
                expected_json=payload["expected_json"],
                min_value=payload["min_value"],
                max_value=payload["max_value"],
                schema_text=payload["schema_text"],
            )
            for payload in _legacy_assertions_to_specs(request.assertions)
        ]
        if assertion_rows:
            ApiAssertionSpec.objects.using(db_alias).bulk_create(assertion_rows)


def _create_test_case_specs(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ApiTestCase = apps.get_model("api_automation", "ApiTestCase")
    ApiTestCaseOverrideSpec = apps.get_model("api_automation", "ApiTestCaseOverrideSpec")
    ApiTestCaseFieldSpec = apps.get_model("api_automation", "ApiTestCaseFieldSpec")
    ApiAssertionSpec = apps.get_model("api_automation", "ApiAssertionSpec")

    for test_case in ApiTestCase.objects.using(db_alias).select_related("request").all().iterator():
        script = test_case.script if isinstance(test_case.script, dict) else {}
        overrides = script.get("request_overrides") if isinstance(script, dict) else {}
        if not isinstance(overrides, dict):
            overrides = {}
        body_type = str(overrides.get("body_type") or "").lower()
        body_mode = LEGACY_TO_BODY_MODE.get(body_type, "")
        body = overrides.get("body")

        override_spec = ApiTestCaseOverrideSpec.objects.using(db_alias).create(
            test_case_id=test_case.id,
            method=str(overrides.get("method") or ""),
            url=str(overrides.get("url") or ""),
            body_mode=body_mode,
            body_json=body if body_mode == "json" and isinstance(body, (dict, list)) else {},
            raw_text=_to_text(body) if body_mode == "raw" else "",
            xml_text="",
            binary_base64="",
            graphql_query="",
            graphql_operation_name="",
            graphql_variables={},
            timeout_ms=overrides.get("timeout_ms"),
        )

        field_rows = []
        field_rows.extend(
            _create_named_field_specs(
                ApiTestCaseFieldSpec,
                "override_spec_id",
                override_spec.id,
                "header",
                overrides.get("headers"),
            )
        )
        field_rows.extend(
            _create_named_field_specs(
                ApiTestCaseFieldSpec,
                "override_spec_id",
                override_spec.id,
                "query",
                overrides.get("params"),
            )
        )
        if body_mode == "form" and isinstance(body, dict):
            field_rows.extend(
                _create_named_field_specs(
                    ApiTestCaseFieldSpec,
                    "override_spec_id",
                    override_spec.id,
                    "form",
                    body,
                )
            )
        if field_rows:
            ApiTestCaseFieldSpec.objects.using(db_alias).bulk_create(field_rows)

        assertion_rows = [
            ApiAssertionSpec(
                test_case_id=test_case.id,
                enabled=payload["enabled"],
                order=payload["order"],
                assertion_type=payload["assertion_type"],
                target=payload["target"],
                selector=payload["selector"],
                operator=payload["operator"],
                expected_text=payload["expected_text"],
                expected_number=payload["expected_number"],
                expected_json=payload["expected_json"],
                min_value=payload["min_value"],
                max_value=payload["max_value"],
                schema_text=payload["schema_text"],
            )
            for payload in _legacy_assertions_to_specs(test_case.assertions)
        ]
        if assertion_rows:
            ApiAssertionSpec.objects.using(db_alias).bulk_create(assertion_rows)


def _create_environment_specs(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ApiEnvironment = apps.get_model("api_automation", "ApiEnvironment")
    ApiEnvironmentVariableSpec = apps.get_model("api_automation", "ApiEnvironmentVariableSpec")
    ApiEnvironmentHeaderSpec = apps.get_model("api_automation", "ApiEnvironmentHeaderSpec")

    for environment in ApiEnvironment.objects.using(db_alias).all().iterator():
        variable_rows = []
        if isinstance(environment.variables, dict):
            for index, (name, value) in enumerate(environment.variables.items()):
                variable_rows.append(
                    ApiEnvironmentVariableSpec(
                        environment_id=environment.id,
                        name=str(name),
                        value=_to_text(value),
                        enabled=True,
                        is_secret=False,
                        order=index,
                    )
                )
        if variable_rows:
            ApiEnvironmentVariableSpec.objects.using(db_alias).bulk_create(variable_rows)

        header_rows = []
        if isinstance(environment.common_headers, dict):
            for index, (name, value) in enumerate(environment.common_headers.items()):
                header_rows.append(
                    ApiEnvironmentHeaderSpec(
                        environment_id=environment.id,
                        name=str(name),
                        value=_to_text(value),
                        enabled=True,
                        order=index,
                    )
                )
        if header_rows:
            ApiEnvironmentHeaderSpec.objects.using(db_alias).bulk_create(header_rows)


def backfill_structured_specs(apps, schema_editor):
    _create_request_specs(apps, schema_editor)
    _create_test_case_specs(apps, schema_editor)
    _create_environment_specs(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0005_apiexecutionrecord_run_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiexecutionrecord',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='执行批次 ID'),
        ),
        migrations.AlterField(
            model_name='apiexecutionrecord',
            name='run_name',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='执行批次名称'),
        ),
        migrations.AlterField(
            model_name='apiexecutionrecord',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='api_automation.apitestcase', verbose_name='关联测试用例'),
        ),
        migrations.CreateModel(
            name='ApiAssertionSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('assertion_type', models.CharField(choices=[('status_code', 'status_code'), ('status_range', 'status_range'), ('body_contains', 'body_contains'), ('body_not_contains', 'body_not_contains'), ('json_path', 'json_path'), ('header', 'header'), ('cookie', 'cookie'), ('regex', 'regex'), ('exists', 'exists'), ('not_exists', 'not_exists'), ('array_length', 'array_length'), ('response_time', 'response_time'), ('json_schema', 'json_schema'), ('openapi_contract', 'openapi_contract')], max_length=40, verbose_name='断言类型')),
                ('target', models.CharField(blank=True, default='body', max_length=40, verbose_name='断言目标')),
                ('selector', models.CharField(blank=True, default='', max_length=500, verbose_name='选择器')),
                ('operator', models.CharField(blank=True, default='equals', max_length=40, verbose_name='运算符')),
                ('expected_text', models.TextField(blank=True, default='', verbose_name='期望文本')),
                ('expected_number', models.FloatField(blank=True, null=True, verbose_name='期望数值')),
                ('expected_json', models.JSONField(blank=True, default=dict, verbose_name='期望 JSON')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='最小值')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='最大值')),
                ('schema_text', models.TextField(blank=True, default='', verbose_name='Schema 文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assertion_specs', to='api_automation.apirequest', verbose_name='所属请求')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assertion_specs', to='api_automation.apitestcase', verbose_name='所属测试用例')),
            ],
            options={
                'verbose_name': 'API 断言规格',
                'verbose_name_plural': 'API 断言规格',
                'db_table': 'api_automation_assertion_spec',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiExtractorSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('source', models.CharField(choices=[('json_path', 'json_path'), ('header', 'header'), ('cookie', 'cookie'), ('regex', 'regex'), ('status_code', 'status_code'), ('response_time', 'response_time')], max_length=40, verbose_name='提取来源')),
                ('selector', models.CharField(blank=True, default='', max_length=500, verbose_name='选择器')),
                ('variable_name', models.CharField(max_length=160, verbose_name='变量名')),
                ('default_value', models.TextField(blank=True, default='', verbose_name='默认值')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractor_specs', to='api_automation.apirequest', verbose_name='所属请求')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractor_specs', to='api_automation.apitestcase', verbose_name='所属测试用例')),
            ],
            options={
                'verbose_name': 'API 提取器规格',
                'verbose_name_plural': 'API 提取器规格',
                'db_table': 'api_automation_extractor_spec',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(verbose_name='请求地址')),
                ('body_mode', models.CharField(choices=[('none', 'none'), ('json', 'json'), ('form', 'form'), ('urlencoded', 'urlencoded'), ('multipart', 'multipart'), ('raw', 'raw'), ('xml', 'xml'), ('graphql', 'graphql'), ('binary', 'binary')], default='none', max_length=20, verbose_name='请求体模式')),
                ('body_json', models.JSONField(blank=True, default=dict, verbose_name='JSON 请求体')),
                ('raw_text', models.TextField(blank=True, default='', verbose_name='原始文本请求体')),
                ('xml_text', models.TextField(blank=True, default='', verbose_name='XML 请求体')),
                ('binary_base64', models.TextField(blank=True, default='', verbose_name='二进制 Base64')),
                ('graphql_query', models.TextField(blank=True, default='', verbose_name='GraphQL Query')),
                ('graphql_operation_name', models.CharField(blank=True, default='', max_length=120, verbose_name='GraphQL Operation')),
                ('graphql_variables', models.JSONField(blank=True, default=dict, verbose_name='GraphQL Variables')),
                ('timeout_ms', models.PositiveIntegerField(default=30000, verbose_name='超时时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_spec', to='api_automation.apirequest', verbose_name='请求规格')),
            ],
            options={
                'verbose_name': 'API 请求规格',
                'verbose_name_plural': 'API 请求规格',
                'db_table': 'api_automation_request_spec',
            },
        ),
        migrations.CreateModel(
            name='ApiRequestFileSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, verbose_name='表单字段名')),
                ('source_type', models.CharField(choices=[('path', 'path'), ('base64', 'base64'), ('placeholder', 'placeholder')], default='path', max_length=20, verbose_name='文件来源')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='文件名')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='文件 Content-Type')),
                ('base64_content', models.TextField(blank=True, default='', verbose_name='文件 Base64 内容')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_specs', to='api_automation.apirequestspec', verbose_name='所属请求规格')),
            ],
            options={
                'verbose_name': 'API 请求文件规格',
                'verbose_name_plural': 'API 请求文件规格',
                'db_table': 'api_automation_request_file_spec',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestFieldSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_kind', models.CharField(choices=[('header', 'header'), ('query', 'query'), ('cookie', 'cookie'), ('form', 'form'), ('multipart_text', 'multipart_text')], max_length=30, verbose_name='字段类型')),
                ('name', models.CharField(max_length=200, verbose_name='字段名')),
                ('value', models.TextField(blank=True, default='', verbose_name='字段值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_specs', to='api_automation.apirequestspec', verbose_name='所属请求规格')),
            ],
            options={
                'verbose_name': 'API 请求字段规格',
                'verbose_name_plural': 'API 请求字段规格',
                'db_table': 'api_automation_request_field_spec',
                'ordering': ['field_kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestAuthSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('none', 'none'), ('basic', 'basic'), ('bearer', 'bearer'), ('api_key', 'api_key'), ('cookie', 'cookie'), ('bootstrap_request', 'bootstrap_request')], default='none', max_length=30, verbose_name='认证类型')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='密码')),
                ('token_value', models.TextField(blank=True, default='', verbose_name='Token 值')),
                ('token_variable', models.CharField(blank=True, default='token', max_length=120, verbose_name='Token 变量名')),
                ('header_name', models.CharField(blank=True, default='Authorization', max_length=120, verbose_name='Header 名')),
                ('bearer_prefix', models.CharField(blank=True, default='Bearer', max_length=40, verbose_name='Bearer 前缀')),
                ('api_key_name', models.CharField(blank=True, default='', max_length=120, verbose_name='API Key 名')),
                ('api_key_in', models.CharField(choices=[('header', 'header'), ('query', 'query'), ('cookie', 'cookie')], default='header', max_length=20, verbose_name='API Key 位置')),
                ('api_key_value', models.TextField(blank=True, default='', verbose_name='API Key 值')),
                ('cookie_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Cookie 名')),
                ('bootstrap_request_id', models.IntegerField(blank=True, null=True, verbose_name='引导请求 ID')),
                ('bootstrap_request_name', models.CharField(blank=True, default='', max_length=160, verbose_name='引导请求名称')),
                ('bootstrap_token_path', models.CharField(blank=True, default='', max_length=255, verbose_name='引导 Token Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request_spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_spec', to='api_automation.apirequestspec', verbose_name='认证规格')),
            ],
            options={
                'verbose_name': 'API 请求认证规格',
                'verbose_name_plural': 'API 请求认证规格',
                'db_table': 'api_automation_request_auth_spec',
            },
        ),
        migrations.CreateModel(
            name='ApiRequestTransportSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='校验证书')),
                ('proxy_url', models.CharField(blank=True, default='', max_length=500, verbose_name='代理地址')),
                ('client_cert', models.CharField(blank=True, default='', max_length=500, verbose_name='客户端证书')),
                ('client_key', models.CharField(blank=True, default='', max_length=500, verbose_name='客户端私钥')),
                ('follow_redirects', models.BooleanField(default=True, verbose_name='跟随重定向')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('retry_interval_ms', models.PositiveIntegerField(default=500, verbose_name='重试间隔(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request_spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_spec', to='api_automation.apirequestspec', verbose_name='传输规格')),
            ],
            options={
                'verbose_name': 'API 请求传输规格',
                'verbose_name_plural': 'API 请求传输规格',
                'db_table': 'api_automation_request_transport_spec',
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseOverrideSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='覆盖请求方法')),
                ('url', models.TextField(blank=True, default='', verbose_name='覆盖请求地址')),
                ('body_mode', models.CharField(blank=True, choices=[('none', 'none'), ('json', 'json'), ('form', 'form'), ('urlencoded', 'urlencoded'), ('multipart', 'multipart'), ('raw', 'raw'), ('xml', 'xml'), ('graphql', 'graphql'), ('binary', 'binary')], default='', max_length=20, verbose_name='覆盖请求体模式')),
                ('body_json', models.JSONField(blank=True, default=dict, verbose_name='覆盖 JSON 请求体')),
                ('raw_text', models.TextField(blank=True, default='', verbose_name='覆盖原始文本')),
                ('xml_text', models.TextField(blank=True, default='', verbose_name='覆盖 XML 请求体')),
                ('binary_base64', models.TextField(blank=True, default='', verbose_name='覆盖二进制 Base64')),
                ('graphql_query', models.TextField(blank=True, default='', verbose_name='覆盖 GraphQL Query')),
                ('graphql_operation_name', models.CharField(blank=True, default='', max_length=120, verbose_name='覆盖 GraphQL Operation')),
                ('graphql_variables', models.JSONField(blank=True, default=dict, verbose_name='覆盖 GraphQL Variables')),
                ('timeout_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='覆盖超时时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override_spec', to='api_automation.apitestcase', verbose_name='所属测试用例')),
            ],
            options={
                'verbose_name': 'API 测试用例覆盖规格',
                'verbose_name_plural': 'API 测试用例覆盖规格',
                'db_table': 'api_automation_test_case_override_spec',
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseFileSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, verbose_name='表单字段名')),
                ('source_type', models.CharField(choices=[('path', 'path'), ('base64', 'base64'), ('placeholder', 'placeholder')], default='path', max_length=20, verbose_name='文件来源')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='文件名')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='文件 Content-Type')),
                ('base64_content', models.TextField(blank=True, default='', verbose_name='文件 Base64 内容')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('override_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_specs', to='api_automation.apitestcaseoverridespec', verbose_name='所属用例覆盖规格')),
            ],
            options={
                'verbose_name': 'API 测试用例文件规格',
                'verbose_name_plural': 'API 测试用例文件规格',
                'db_table': 'api_automation_test_case_file_spec',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseFieldSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_kind', models.CharField(choices=[('header', 'header'), ('query', 'query'), ('cookie', 'cookie'), ('form', 'form'), ('multipart_text', 'multipart_text')], max_length=30, verbose_name='字段类型')),
                ('name', models.CharField(max_length=200, verbose_name='字段名')),
                ('value', models.TextField(blank=True, default='', verbose_name='字段值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('override_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_specs', to='api_automation.apitestcaseoverridespec', verbose_name='所属用例覆盖规格')),
            ],
            options={
                'verbose_name': 'API 测试用例字段规格',
                'verbose_name_plural': 'API 测试用例字段规格',
                'db_table': 'api_automation_test_case_field_spec',
                'ordering': ['field_kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseAuthSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(blank=True, choices=[('none', 'none'), ('basic', 'basic'), ('bearer', 'bearer'), ('api_key', 'api_key'), ('cookie', 'cookie'), ('bootstrap_request', 'bootstrap_request')], default='', max_length=30, verbose_name='认证类型')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='密码')),
                ('token_value', models.TextField(blank=True, default='', verbose_name='Token 值')),
                ('token_variable', models.CharField(blank=True, default='', max_length=120, verbose_name='Token 变量名')),
                ('header_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Header 名')),
                ('bearer_prefix', models.CharField(blank=True, default='', max_length=40, verbose_name='Bearer 前缀')),
                ('api_key_name', models.CharField(blank=True, default='', max_length=120, verbose_name='API Key 名')),
                ('api_key_in', models.CharField(choices=[('header', 'header'), ('query', 'query'), ('cookie', 'cookie')], default='header', max_length=20, verbose_name='API Key 位置')),
                ('api_key_value', models.TextField(blank=True, default='', verbose_name='API Key 值')),
                ('cookie_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Cookie 名')),
                ('bootstrap_request_id', models.IntegerField(blank=True, null=True, verbose_name='引导请求 ID')),
                ('bootstrap_request_name', models.CharField(blank=True, default='', max_length=160, verbose_name='引导请求名称')),
                ('bootstrap_token_path', models.CharField(blank=True, default='', max_length=255, verbose_name='引导 Token Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('override_spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_spec', to='api_automation.apitestcaseoverridespec', verbose_name='所属用例覆盖规格')),
            ],
            options={
                'verbose_name': 'API 测试用例认证规格',
                'verbose_name_plural': 'API 测试用例认证规格',
                'db_table': 'api_automation_test_case_auth_spec',
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseTransportSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_ssl', models.BooleanField(blank=True, null=True, verbose_name='校验证书')),
                ('proxy_url', models.CharField(blank=True, default='', max_length=500, verbose_name='代理地址')),
                ('client_cert', models.CharField(blank=True, default='', max_length=500, verbose_name='客户端证书')),
                ('client_key', models.CharField(blank=True, default='', max_length=500, verbose_name='客户端私钥')),
                ('follow_redirects', models.BooleanField(blank=True, null=True, verbose_name='跟随重定向')),
                ('retry_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='重试次数')),
                ('retry_interval_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='重试间隔(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('override_spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_spec', to='api_automation.apitestcaseoverridespec', verbose_name='所属用例覆盖规格')),
            ],
            options={
                'verbose_name': 'API 测试用例传输规格',
                'verbose_name_plural': 'API 测试用例传输规格',
                'db_table': 'api_automation_test_case_transport_spec',
            },
        ),
        migrations.CreateModel(
            name='ApiEnvironmentCookieSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Cookie 名')),
                ('value', models.TextField(blank=True, default='', verbose_name='Cookie 值')),
                ('domain', models.CharField(blank=True, default='', max_length=255, verbose_name='Domain')),
                ('path', models.CharField(blank=True, default='/', max_length=255, verbose_name='Path')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_specs', to='api_automation.apienvironment', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': 'API 环境 Cookie 规格',
                'verbose_name_plural': 'API 环境 Cookie 规格',
                'db_table': 'api_automation_environment_cookie_spec',
                'ordering': ['order', 'id'],
                'unique_together': {('environment', 'name', 'domain', 'path')},
            },
        ),
        migrations.CreateModel(
            name='ApiEnvironmentHeaderSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Header 名')),
                ('value', models.TextField(blank=True, default='', verbose_name='Header 值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_specs', to='api_automation.apienvironment', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': 'API 环境 Header 规格',
                'verbose_name_plural': 'API 环境 Header 规格',
                'db_table': 'api_automation_environment_header_spec',
                'ordering': ['order', 'id'],
                'unique_together': {('environment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApiEnvironmentVariableSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='变量名')),
                ('value', models.TextField(blank=True, default='', verbose_name='变量值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否敏感')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_specs', to='api_automation.apienvironment', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': 'API 环境变量规格',
                'verbose_name_plural': 'API 环境变量规格',
                'db_table': 'api_automation_environment_variable_spec',
                'ordering': ['order', 'id'],
                'unique_together': {('environment', 'name')},
            },
        ),
        migrations.RunPython(backfill_structured_specs, migrations.RunPython.noop),
    ]
