# Generated by Django 5.2 on 2026-03-30 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='集合名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_collections', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_automation.apicollection', verbose_name='父集合')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_collections', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API 集合',
                'verbose_name_plural': 'API 集合',
                'db_table': 'api_automation_collection',
                'ordering': ['order', 'created_at'],
                'unique_together': {('project', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApiEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('base_url', models.CharField(blank=True, default='', max_length=500, verbose_name='基础地址')),
                ('common_headers', models.JSONField(blank=True, default=dict, verbose_name='公共请求头')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='环境变量')),
                ('timeout_ms', models.PositiveIntegerField(default=30000, verbose_name='默认超时(ms)')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_environments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_environments', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API 环境',
                'verbose_name_plural': 'API 环境',
                'db_table': 'api_automation_environment',
                'ordering': ['project', '-is_default', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='请求名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='请求描述')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(verbose_name='请求地址')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='查询参数')),
                ('body_type', models.CharField(choices=[('none', 'none'), ('json', 'json'), ('form', 'form'), ('raw', 'raw')], default='none', max_length=20, verbose_name='请求体类型')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('assertions', models.JSONField(blank=True, default=list, verbose_name='断言规则')),
                ('timeout_ms', models.PositiveIntegerField(default=30000, verbose_name='超时时间(ms)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api_automation.apicollection', verbose_name='所属集合')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_requests', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'API 请求',
                'verbose_name_plural': 'API 请求',
                'db_table': 'api_automation_request',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=120, verbose_name='请求名称')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(verbose_name='最终地址')),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('error', 'error')], default='success', max_length=20, verbose_name='执行状态')),
                ('passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('request_snapshot', models.JSONField(blank=True, default=dict, verbose_name='请求快照')),
                ('response_snapshot', models.JSONField(blank=True, default=dict, verbose_name='响应快照')),
                ('assertions_results', models.JSONField(blank=True, default=list, verbose_name='断言结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='api_automation.apienvironment', verbose_name='执行环境')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_execution_records', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_execution_records', to='projects.project', verbose_name='所属项目')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='api_automation.apirequest', verbose_name='所属请求')),
            ],
            options={
                'verbose_name': 'API 执行记录',
                'verbose_name_plural': 'API 执行记录',
                'db_table': 'api_automation_execution_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
